"""Add FeedbackModel

Revision ID: 73f17dec63d5
Revises: 937ebadd40bc
Create Date: 2026-04-19 13:26:49.811561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f17dec63d5'
down_revision: Union[str, None] = '937ebadd40bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('overall_risk', sa.Float(), nullable=True),
    sa.Column('suspicious_chunks_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_document_id'), 'documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_tenant_id'), 'documents', ['tenant_id'], unique=False)
    op.create_table('scan_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('app_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('raw_prompt', sa.Text(), nullable=False),
    sa.Column('normalized_prompt', sa.Text(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_requests_app_id'), 'scan_requests', ['app_id'], unique=False)
    op.create_index(op.f('ix_scan_requests_id'), 'scan_requests', ['id'], unique=False)
    op.create_index(op.f('ix_scan_requests_request_id'), 'scan_requests', ['request_id'], unique=False)
    op.create_index(op.f('ix_scan_requests_tenant_id'), 'scan_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_scan_requests_trace_id'), 'scan_requests', ['trace_id'], unique=True)
    op.create_index(op.f('ix_scan_requests_user_id'), 'scan_requests', ['user_id'], unique=False)
    op.create_table('url_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('url_id', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('overall_risk', sa.Float(), nullable=True),
    sa.Column('suspicious_chunks_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_sources_id'), 'url_sources', ['id'], unique=False)
    op.create_index(op.f('ix_url_sources_tenant_id'), 'url_sources', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_url_sources_url_id'), 'url_sources', ['url_id'], unique=False)
    op.create_table('canary_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('request_fk', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('canary_token', sa.String(), nullable=False),
    sa.Column('inserted', sa.Boolean(), nullable=True),
    sa.Column('insertion_location', sa.String(), nullable=True),
    sa.Column('leaked', sa.Boolean(), nullable=True),
    sa.Column('leaked_in_output_excerpt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_fk'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canary_events_canary_token'), 'canary_events', ['canary_token'], unique=True)
    op.create_index(op.f('ix_canary_events_id'), 'canary_events', ['id'], unique=False)
    op.create_index(op.f('ix_canary_events_trace_id'), 'canary_events', ['trace_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_fk', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('attack_type', sa.String(), nullable=True),
    sa.Column('quarantined', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['document_fk'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_chunk_id'), 'document_chunks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=False),
    sa.Column('request_fk', sa.Integer(), nullable=True),
    sa.Column('label', sa.Enum('true_positive', 'false_positive', 'false_negative', 'benign', 'needs_review', name='feedbacklabel'), nullable=False),
    sa.Column('reviewer', sa.String(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['request_fk'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_index(op.f('ix_feedbacks_trace_id'), 'feedbacks', ['trace_id'], unique=False)
    op.create_table('output_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('request_fk', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('llm_called', sa.Boolean(), nullable=True),
    sa.Column('output_action', sa.String(), nullable=True),
    sa.Column('block_reason', sa.String(), nullable=True),
    sa.Column('safe_excerpt', sa.Text(), nullable=True),
    sa.Column('output_hash', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('redacted', sa.Boolean(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('canary_leaked', sa.Boolean(), nullable=True),
    sa.Column('secret_detected', sa.Boolean(), nullable=True),
    sa.Column('pii_detected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['request_fk'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_scans_id'), 'output_scans', ['id'], unique=False)
    op.create_index(op.f('ix_output_scans_trace_id'), 'output_scans', ['trace_id'], unique=False)
    op.create_table('scan_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_fk', sa.Integer(), nullable=True),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('sanitized_content', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['request_fk'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_channels_id'), 'scan_channels', ['id'], unique=False)
    op.create_table('url_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_source_fk', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('attack_type', sa.String(), nullable=True),
    sa.Column('quarantined', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['url_source_fk'], ['url_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_url_chunks_chunk_id'), 'url_chunks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_url_chunks_id'), 'url_chunks', ['id'], unique=False)
    op.create_table('scan_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_fk', sa.Integer(), nullable=True),
    sa.Column('channel_fk', sa.Integer(), nullable=True),
    sa.Column('scanner_name', sa.String(), nullable=False),
    sa.Column('attack_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('matched_text', sa.String(), nullable=True),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['channel_fk'], ['scan_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_fk'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_detections_id'), 'scan_detections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_detections_id'), table_name='scan_detections')
    op.drop_table('scan_detections')
    op.drop_index(op.f('ix_url_chunks_id'), table_name='url_chunks')
    op.drop_index(op.f('ix_url_chunks_chunk_id'), table_name='url_chunks')
    op.drop_table('url_chunks')
    op.drop_index(op.f('ix_scan_channels_id'), table_name='scan_channels')
    op.drop_table('scan_channels')
    op.drop_index(op.f('ix_output_scans_trace_id'), table_name='output_scans')
    op.drop_index(op.f('ix_output_scans_id'), table_name='output_scans')
    op.drop_table('output_scans')
    op.drop_index(op.f('ix_feedbacks_trace_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_canary_events_trace_id'), table_name='canary_events')
    op.drop_index(op.f('ix_canary_events_id'), table_name='canary_events')
    op.drop_index(op.f('ix_canary_events_canary_token'), table_name='canary_events')
    op.drop_table('canary_events')
    op.drop_index(op.f('ix_url_sources_url_id'), table_name='url_sources')
    op.drop_index(op.f('ix_url_sources_tenant_id'), table_name='url_sources')
    op.drop_index(op.f('ix_url_sources_id'), table_name='url_sources')
    op.drop_table('url_sources')
    op.drop_index(op.f('ix_scan_requests_user_id'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_trace_id'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_tenant_id'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_request_id'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_id'), table_name='scan_requests')
    op.drop_index(op.f('ix_scan_requests_app_id'), table_name='scan_requests')
    op.drop_table('scan_requests')
    op.drop_index(op.f('ix_documents_tenant_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
