"""Add output and canary models

Revision ID: 937ebadd40bc
Revises: 001_initial_schema
Create Date: 2026-04-19 12:58:30.298740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937ebadd40bc'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canary_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('request_fk', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('canary_token', sa.String(), nullable=False),
    sa.Column('inserted', sa.Boolean(), nullable=True),
    sa.Column('insertion_location', sa.String(), nullable=True),
    sa.Column('leaked', sa.Boolean(), nullable=True),
    sa.Column('leaked_in_output_excerpt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_fk'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canary_events_canary_token'), 'canary_events', ['canary_token'], unique=True)
    op.create_index(op.f('ix_canary_events_id'), 'canary_events', ['id'], unique=False)
    op.create_index(op.f('ix_canary_events_trace_id'), 'canary_events', ['trace_id'], unique=False)
    op.create_table('output_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.String(), nullable=True),
    sa.Column('request_fk', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('llm_called', sa.Boolean(), nullable=True),
    sa.Column('output_action', sa.String(), nullable=True),
    sa.Column('block_reason', sa.String(), nullable=True),
    sa.Column('safe_excerpt', sa.Text(), nullable=True),
    sa.Column('output_hash', sa.String(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('redacted', sa.Boolean(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('canary_leaked', sa.Boolean(), nullable=True),
    sa.Column('secret_detected', sa.Boolean(), nullable=True),
    sa.Column('pii_detected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['request_fk'], ['scan_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_output_scans_id'), 'output_scans', ['id'], unique=False)
    op.create_index(op.f('ix_output_scans_trace_id'), 'output_scans', ['trace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_output_scans_trace_id'), table_name='output_scans')
    op.drop_index(op.f('ix_output_scans_id'), table_name='output_scans')
    op.drop_table('output_scans')
    op.drop_index(op.f('ix_canary_events_trace_id'), table_name='canary_events')
    op.drop_index(op.f('ix_canary_events_id'), table_name='canary_events')
    op.drop_index(op.f('ix_canary_events_canary_token'), table_name='canary_events')
    op.drop_table('canary_events')
    # ### end Alembic commands ###
